% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Oct-2018 17:13:40
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
                                  

def = struct;
def.ictalcogbaseline = struct;
def.ictalcogbaseline.skip_before = 0;
def.ictalcogbaseline.skip_after = 0;
def.ictalcogbaseline.thresh_dur = 0.01;
def.ictalcogbaseline.listcond = cell(1, 3);
def.ictalcogbaseline.listcond{1} = 'Cond1';
def.ictalcogbaseline.listcond{2} = 'Cond2';
def.ictalcogbaseline.listcond{3} = 'ITI';

