% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Oct-2018 13:33:24
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
                                  

def = struct;
def.emotionf_newbl = struct;
def.emotionf_newbl.skip_before = 0;
def.emotionf_newbl.skip_after = 0;
def.emotionf_newbl.thresh_dur = 0.01;
def.emotionf_newbl.listcond = cell(1, 4);
def.emotionf_newbl.listcond{1} = 'ITI';
def.emotionf_newbl.listcond{2} = 'Negative';
def.emotionf_newbl.listcond{3} = 'Positive';
def.emotionf_newbl.listcond{4} = 'Neutral';

