% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Oct-2018 15:21:16
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
                                  

def = struct;
def.new_test = struct;
def.new_test.skip_before = 0;
def.new_test.skip_after = 0;
def.new_test.thresh_dur = 0.01;
def.new_test.listcond = cell(1, 3);
def.new_test.listcond{1} = 'B';
def.new_test.listcond{2} = 'W';
def.new_test.listcond{3} = 'A';

