% MMR
% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Sep-2018 01:37:46
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
                                   

% MMR
def = struct;
def.mynewtask = struct;
def.mynewtask.skip_before = 12;
def.mynewtask.skip_after = 0;
def.mynewtask.thresh_dur = 0.01;
def.mynewtask.listcond = cell(1, 4);
def.mynewtask.listcond{1} = 'Cond1';
def.mynewtask.listcond{2} = 'Cond2';
def.mynewtask.listcond{3} = 'Cond3';
def.mynewtask.listcond{4} = 'Cond4';

