function out = timer_getinfo(task,sbj)
S.fh = figure('units','pixels',...
    'position',[1000 600 230 200],...
    'menubar','none',...
    'name','Data Information',...
    'numbertitle','off',...
    'resize','off');
S.tx = uicontrol('style','text',...
    'unit','pix',...
    'position',[160 27 30 30],...
    'fontsize',14,...
    'string','5','FontName','Optima');
in = sprintf('%s\n\n\n%s\n\n\n%s','Task name:','Subject ID: ');
S.tx2 = uicontrol('style','text',...
    'unit','pix',...
    'position',[7 100 200 80],...
    'fontsize',14,...
    'string',in,'FontName','Optima');

S.input = uicontrol('style','edit',...
    'unit','pix',...
    'position',[15 85 180 20],...
    'fontsize',14,...
    'string',sbj,'FontName','Optima','enable','off');
S.input2 = uicontrol('style','edit',...
    'unit','pix',...
    'position',[15 140 180 20],...
    'fontsize',14,...
    'string',task,'FontName','Optima','enable','off');
out.task=task;
out.sname=sbj;
setappdata(S.fh,'out',out);
S.tmr = timer('Name','Countdown',...
    'Period',1,...  % 10 minute snooze time.
    'StartDelay',.01,...
    'ExecutionMode','fixedSpacing',...
    'StopFcn',@deleter);   % Function def. below.
S.pb = uicontrol('style','push',...
    'units','pix',...
    'position',[10 30 150 30],...
    'fontsize',14,...
    'string','Click to change','FontName','Optima',...
    'callback',{@pb_call,S});
set(S.tmr,'TimerFcn',{@update_disp,S});
set(S.tmr,'TasksToExecute',str2double(get(S.tx,'string'))) ;
if ~isempty(out.task) && ~isempty(out.sname)
    start(S.tmr);
    waitfor(S.fh,'name');
    
    %close(S.fh);
else
    pb_call(S.pb,[],S);
    waitfor(S.fh,'name');
    %close(S.fh);
end
out = getappdata(S.fh,'out');
delete(S.fh);

function pb_call(varargin)
% Callback for pushbutton, deletes one line from listbox.

S = varargin{3};
obj = varargin{1};
stop(S.tmr);
set(S.input,'enable','on');
set(S.input2,'enable','on');
set(S.tx,'string','');
set(obj,'string','Done','FontName','Optima',...
    'callback',{@pb_call2,S});



% Need to check string!
% set(S.tmr,'TasksToExecute',str2double(get(S.tx,'string')))
% start(S.tmr);
function [] = update_disp(varargin)
S = varargin{3};
N = str2double(get(S.tx,'string'));
set(S.tx,'string',num2str(N-1));
if N == 1
    set(S.fh,'name','Closing');
    %close(S.fh);
end
function deleter(obj,edata)   %#ok   M-Lint doesn't know the callback fmt.
% Callback for stopfcn.
wait(obj);
delete(obj);

function out = pb_call2(varargin)
S = varargin{3};
out.task=get(S.input2,'string');
out.sname=get(S.input,'string');
setappdata(S.fh,'out',out);
set(S.fh,'name','Closing');
%close(S.fh);